Feature/tags table
kotarou1192/Co-review pull request #20
Opened 2020-02-05 19:46 UTC by kotarou1192

## 色々やってみたのでよかったら見てみてください。まずいところは直します。
## やったこと
* タグ空白で区切って10個まで追加できるようにした
→`MAX_TAG_AMOUNT = 10`にて設定できます。
* タグ関連のエラーメッセージもちゃんと表示されるようにした
→`@review_request.errors.add 'tag_error:', e.message`にて設定
* タグの長さは最大16文字
→`MAX_TAG_SIZE = 16`にて設定できます。
* 同じ名前のタグを同時に複数登録するとエラー表示して弾くようにした
* 投稿失敗で画面が遷移してもタグの内容を保持するようにした
→value="<%=@tags%>"にて、タグの内容を変数に格納しておいたものを呼び出しています。

## レビューしてほしいポイント
なにかマズい事をしていないかが気になっています。例外処理を施したのですが、その辺りが一番不安です。（使うの初めてなので）  
また、いつもながら命名が不安なので指摘してください。  
エラーメッセージも英語で書いてみましたが不安です。  
とりあえず出来上がったかなと思ったのでPR出してみました、不安点多いですがよろしくお願いします

## なぜ例外を使ったか
いちばんスマートにできるかなと思ったため。

2020-02-06 08:23 UTC, nimuC commented on app/views/review_requests/new.html.erb
> +      <div class="post-request post-request__interface_text">タグを半角スペース区切りで入力
BEMという命名規則に従って、私はclassを命名しました。
BEMを使っているというのを伝え忘れた、私のミスです。
できれば、その規則に従って命名してほしいです。
[BEMについて](https://app.codegrid.net/entry/bem-basic-1)

2020-02-06 08:23 UTC, nimuC commented on app/views/review_requests/new.html.erb
> +      <div class="post-request post-request__interface_text">本文を入力</div>
このような文字を追加する場合は、pタグ、もしくは labelタグ を使うことが多いような気がします。
なにか理由があれば、教えてほしいです。

もしかして、30 から 32 行目と同じような書き方にしたかったという理由ですか?
```html
<div class="post-request post-request__interface_text">本文を入力
  <%= f.text_area :text,
    class: "post-request__interface post-request__interface_input-text" %>
</div>
```

2020-02-06 08:57 UTC, kotarou1192 commented on app/views/review_requests/new.html.erb
> +      <div class="post-request post-request__interface_text">本文を入力</div>
正直言ってまだHTML, CSS共によくわかっていないので（やっつけで書きました）使い分けがイマイチわかっていません。
調べてみたのですがpは上下に自動でスペースが追加され、文章によく使うということだけわかりました。
divではいけない理由って具体的にどう言ったところなのでしょうか。

2020-02-06 08:59 UTC, kotarou1192 commented on app/views/review_requests/new.html.erb
> +      <div class="post-request post-request__interface_text">タグを半角スペース区切りで入力
了解しました。書き直してみます。

2020-02-06 09:51 UTC, nimuC commented on app/views/review_requests/new.html.erb
> +      <div class="post-request post-request__interface_text">本文を入力</div>
pタグの使用用途は、主に文章を記述することです。非常に限定的です。
divタグの使用方法は、主にdivタグ含むブロック要素や、インライン要素をまとめることです。割と汎用的です。

```html
 <div class="post-request post-request__interface_text">本文を入力</div>
```

私が指摘したコードを見ると、divタグに文字が直接が書かれているだけです。
文章を書くためのpタグという存在があるのに、それを使わないのは少し違和感がありませんか?
それに、本来のdivタグの役割を果たしていません。
labelタグ、もしくは pタグ を使うほうが無難ではないでしょうか。というのが私の違憲です。

2020-02-06 09:54 UTC, kotarou1192 commented on app/views/review_requests/new.html.erb
> +      <div class="post-request post-request__interface_text">本文を入力</div>
納得しました。pタグ使いますね、書き直しておきます。
ありがとうございます。

2020-02-06 09:57 UTC, nimuC commented on app/views/review_requests/new.html.erb
> +      <div class="post-request post-request__interface_text">タグを半角スペース区切りで入力
すみません、もう一つ修正箇所あります。
```html
<div class="post-request post-request__interface_text">タグを半角スペース区切りで入力
```
このdivタグがpost-requestクラスに属しています。
これは、post-requestクラスのCSSがそのまま適用されちゃうので、良くないですね。
可読性的にも。

2020-02-06 10:09 UTC, kotarou1192 commented on app/views/review_requests/new.html.erb
> +      <div class="post-request post-request__interface_text">タグを半角スペース区切りで入力
このpost-requestをなくしたり変更すると表示が崩れてしまいます。
名前を変えてクラスを定義し直すべきですか？

2020-02-06 10:17 UTC, nimuC commented on app/views/review_requests/new.html.erb
> +      <div class="post-request post-request__interface_text">タグを半角スペース区切りで入力
そうですね。
```      html
<div class="post-request post-request__interface_text">タグを半角スペース区切りで入力
  <input id="tags" name="tags" type="text" class="post-request__interface post- 
request__interface_input-tags">
</div>
```
それと、このdivタグは、inputエレメントを含んでいるので、完全にブロック要素ですよね。
なので、`post-request__interface_text`という命名は少し不思議に感じます。

それと、インプットタグに説明を追加してる他の例がありますよね。
```html
      <p class="post-request post-request__interface_text">本文を入力</p>
```
実装の仕方がそれぞれ違うのも、少し違和感を覚えます。
何かしらの理由があるなら、説明して欲しいです。
特に理由がないのであれば、どちらかに統一して欲した方が綺麗かなと思います。(最後に、今気づきましたが、この要素もpost-requestクラスに属していますね。)

2020-02-06 10:34 UTC, kotarou1192 commented on app/views/review_requests/new.html.erb
> +      <div class="post-request post-request__interface_text">タグを半角スペース区切りで入力
```css
<div class="post-request">
   <p class="post-request__text">タグを半角スペース区切りで入力</p>
   <input id="tags" name="tags" value="<% =@tags %>" type="text" class="post-request__interface post-request__interface_input-tags">
</div>
```

これでどうでしょうか？

2020-02-06 10:35 UTC, nimuC commented on app/views/review_requests/new.html.erb
> +      <div class="post-request post-request__interface_text">タグを半角スペース区切りで入力
💯

2020-02-06 10:59 UTC, kotarou1192 commented on app/views/review_requests/new.html.erb
> +      <div class="post-request post-request__interface_text">タグを半角スペース区切りで入力
上記のコードのうち、divタグを削除してプッシュしました。

2020-02-09 14:00 UTC, kotarou1192 commented
BEM式にするためにはたぶんnew.html.erbで使ってるCSSを全部書き換えないといけないのでそこはもう自分は編集せずにむCに任せたいと思います。
バックエンド的なところだけ見ていただければ幸いです

2020-02-12 14:56 UTC, ghost reviewed
気になる部分にコメントしたよ

2020-02-12 14:56 UTC, radix-soup commented on app/controllers/review_requests_controller.rb
>      # p params
デバッグ用の `p` をコメントアウトするなら，出力結果まで付記してくれると超嬉しい

2020-02-12 14:56 UTC, radix-soup commented on app/controllers/review_requests_controller.rb
> +      render action: :new
nice!

2020-02-12 14:56 UTC, radix-soup commented on app/controllers/review_requests_controller.rb
> +      return
この `return` がなぜ必要かわかる？(理解の確認がしたいだけ，知らなかったら調べてね)

2020-02-12 14:56 UTC, radix-soup commented on app/controllers/review_requests_controller.rb
>    def create
ちょっと `create` 内のコード量が多いかな
どうやったらメソッド内に直接記述するコード量を減らせるか考えよう

2020-02-12 14:56 UTC, radix-soup commented on app/controllers/review_requests_controller.rb
> +    # for safety, choose only required parameters
nice~!

2020-02-12 14:56 UTC, radix-soup commented on app/controllers/review_requests_controller.rb
>    def create
あとこれ `create!` じゃないかな
FYI: https://web-nari.net/2018/07/13/ruby-on-rails-crud-2/

2020-02-13 02:27 UTC, kotarou1192 commented on app/controllers/review_requests_controller.rb
> +      return
それ以下を実行しないために付けました

2020-02-13 03:42 UTC, kotarou1192 commented on app/controllers/review_requests_controller.rb
>    def create
id = @review_request.idをそのままメソッドの引数に記述すれば短くなりますね。

create!はメソッドの宣言のことですか？
恐らくこのcreate!はモデルに対しての操作のことじゃないかなって思います

2020-02-13 03:49 UTC, kotarou1192 commented on app/controllers/review_requests_controller.rb
>    def create
tags_valid?
とかいうメソッドを作って例外処理部分を放り込むのもいいかもしれません。少し考えてみます

2020-02-13 03:49 UTC, kotarou1192 commented on app/controllers/review_requests_controller.rb
>      # p params
了解です、そのまま張り付けてみますね

2020-02-13 04:41 UTC, radix-soup commented on app/controllers/review_requests_controller.rb
>    def create
> id = @review_request.idをそのままメソッドの引数に記述すれば短くなりますね。
> 
> create!はメソッドの宣言のことですか？
> 恐らくこのcreate!はモデルに対しての操作のことじゃないかなって思います

sorry, 僕のミス，忘却して

2020-02-13 05:35 UTC, kotarou1192 commented
テスト書いたほうが絶対やりやすいけどテスト別のを使うと聞いたので（minitestじゃないやつ）書かずにおいておきました。
とりあえずやったことは
* createメソッドを短くした（2つメソッドを追加しました: are_tags_valid?, finish_createing_review_request）
* p params　の出力内容をメモした
* 少しの間違いの修正

2020-02-13 09:36 UTC, kotarou1192 commented
parmsの中身やそもそもコントローラー自体の仕様についてメモ
https://railsguides.jp/action_controller_overview.html

2020-02-13 11:30 UTC, ikngtty commented
> Make review_request_controller.rb better
IMO: コミットメッセージに一意性がないのでもうちょっと詳しく書いてほしい。最悪2行目以降でも可。

2020-02-16 06:46 UTC, kotarou1192 commented
are_tags_valid?をall_tags_valid?にしました

2020-02-16 07:19 UTC, ikngtty commented
[Q] 完全に Rails 詳しくない人の質問だけど、models/tag.rb はプロパティの定義しないでいいんだっけ？（動いてるみたいだから行けるんだろうけど、なんで行けるんや！？みたいになってる）。

2020-02-16 07:47 UTC, kotarou1192 commented
> [Q] 完全に Rails 詳しくない人の質問だけど、models/tag.rb はプロパティの定義しないでいいんだっけ？（動いてるみたいだから行けるんだろうけど、なんで行けるんや！？みたいになってる）。  

そこはバリデーション書くべき場所なのですが、今回の場合は特に何もなくてもおｋだったので（タグがない場合等ある）書きませんでした。
タグの同時登録については例外で処理しているので総合的に多分問題ないと思います。

2020-02-16 08:08 UTC, ikngtty requested changes

2020-02-16 08:08 UTC, ikngtty commented on app/controllers/review_requests_controller.rb
> +  MAX_TAG_SIZE = 16
[Q] 16 文字？16 バイト？

2020-02-16 08:08 UTC, ikngtty commented on app/controllers/review_requests_controller.rb
> +      Tag.new(tag_name: tag, request_id: id, is_pinned: true)
[Q] デフォルトで `is_pinned` が true なのは違和感あるけど、合ってるの？
（`is_pinned` は投稿者本人以外が弄れない固定タグのことだと認識してる。）

2020-02-16 08:08 UTC, ikngtty commented on app/controllers/review_requests_controller.rb
> +  def create_tag_record(id = nil)
[NITS] やっぱ例外は避けた方がいいね。
この関数は「タグレコードを作ったあと、それのバリデーションをチェックする」っていう役割を担っているので、作ったタグレコードも、バリデーション結果も返さなきゃいけない。そんな時に、片方を例外で表現するのは確かにスマートな解決法に思えるかもしれない。
でも、そもそもなんで返さなきゃいけない情報が２つもあるのかっていえば、役割を２つ担っちゃってるからなんだよね。ここがそもそもスマートじゃない。
もしかしたら、「タグレコードを作ってからじゃないとバリデーションチェックできないから、両方同時にやらないといけない」みたいな思い込みがあったのかもしれない。でも、落ち着いて考えて欲しい。「タグレコードを作ってから」「バリデーションチェック」できるよね。

2020-02-16 08:08 UTC, ikngtty commented on app/controllers/review_requests_controller.rb
> +      raise ArgumentError, 'tag size is too long' if tag.size > MAX_TAG_SIZE
[NITS] タグ単体についてのバリデーションチェックは `models/tag.rb` の中でやった方がすっきりするし、使い回しも効く。

2020-02-16 08:08 UTC, ikngtty commented on app/controllers/review_requests_controller.rb
> +    raise ArgumentError, 'duplicate tag name' if same_name?(all_tags)
[NITS] バリデーションチェックはなるべく Model 層に寄せた方がいい。ただ、入力されたタグ群に関しては、今ある `Tag` クラスの中にはうまくメソッドを用意できないと思う。
こういう時はタグ群を持ってるクラスの方でバリデーションチェックをするのがいい。この場合は `ReviewRequest` クラスかな。
ちなみに `Tag` クラスだけでなく `TagList` みたいなクラスも作っちゃう、というやり方もある。（もっと良い命名ありそう。）タグ群に関するロジックがいっぱい出てきてごちゃごちゃした時とか、`ReviewRequest` 以外のクラスにも"タグ群"の概念が使い回せそうになった時とかは検討するといいと思う。

2020-02-16 08:08 UTC, ikngtty commented on app/controllers/review_requests_controller.rb
> +  def same_name?(all_tags)
[NITS] 何について `same_name` かどうかを調べているのだろう。
まあ確かに、引数を見れば `all_tags` についてなのは分かる。逆にいえばここを見ないとわからない。本当は名前を見ただけで分かるべきだ。
また、他に `same_name` かどうかを調べなきゃいけないものが出てきたらどうするのだろう。例えば「タグ」と「ジャンル」を別の概念として実装しよう、ってなった時とか。

```rb
def same_name?(all_tags) do end
def same_name?(all_genres) do end
```

とすることは、Ruby ではできない。

解決案１：`same_name_tag?` と言った名前にする。`tag_duplicate?` とかの方がより正確かもしれない。
解決案２：そもそもこの手のロジックはモデルに移すべきだ。モデルに移せば、`ReviewRequestController#same_name?` ではなく、`TagList#same_name?` などとなったりする。それなら「これはタグについてのメソッドなんだ」とわざわざ説明しなくても伝わりやすくなるだろう。

2020-02-16 08:08 UTC, ikngtty commented on app/controllers/review_requests_controller.rb
> +    !(all_tags.size - all_tags.uniq.size).zero?
[MUST] `uniq` で same_name なものを検出するのは怪しすぎる。
第一に、name 以外も全部一致していないと重複とは見做されないはずだ。今はたまたま他も全部一致するからなんとかなっているが、少し状況が変われば使えなくなるロジックのように思える。
第二に、そもそもオブジェクト同士の比較で値が一致したら重複と見做されるのだろうか。object_id が違うから違うと見做されるんじゃないだろうか。Ruby の仕様や ActiveRecord の仕様に詳しくなれば、そこは判断つくのかもしれない。まあしかし、そこまで細かい仕様を把握してないといけないロジックというのは、個人的には怖い。

2020-02-16 08:08 UTC, ikngtty commented on app/views/review_requests/new.html.erb
> +      <input id="tags" name="tags" value="<%= @tags %>" type="text" class="post-request__interface post-request__interface_input-tags">
[Q] `@tags` はエスケープしなくて大丈夫？例えばタグの名前にダブルクォーテーションを１文字だけ含めたりしても、正しく動く？

2020-02-16 08:08 UTC, ikngtty commented on app/views/review_requests/new.html.erb
> +      <input id="tags" name="tags" value="<%= @tags %>" type="text" class="post-request__interface post-request__interface_input-tags">
[IMO] `@tags` と聞くと、型は Tag クラスのリストなんだろうなと期待してしまう。
実際にここにくるのは、「タグの名前を半角スペース区切りにしたテキスト」だろうか。
だとしたら、`@tag_names_text` とかの方が正確に伝わるように思う。コントローラー側でも混乱を防げそう。

2020-02-16 08:12 UTC, ikngtty requested changes

2020-02-16 08:12 UTC, ikngtty commented on app/controllers/review_requests_controller.rb
> +    raise ArgumentError, 'too many tags' if all_tags.size > MAX_TAGS_AMOUNT
[MUST] タグの上限はエラーメッセージで教えてあげた方がいい。あとページのどこかにも書いた方が。

2020-02-16 08:13 UTC, kotarou1192 commented on app/controllers/review_requests_controller.rb
> +      raise ArgumentError, 'tag size is too long' if tag.size > MAX_TAG_SIZE
バリデーションの中に確かに文字制限を含めることはできるんですけど、一度の登録内容のユニークさを判断するのって厳しくないです？

2020-02-16 08:14 UTC, ikngtty commented on app/controllers/review_requests_controller.rb
> +      raise ArgumentError, 'tag size is too long' if tag.size > MAX_TAG_SIZE
「"タグ単体についての"バリデーションチェックは」

2020-02-16 08:15 UTC, ikngtty commented on app/controllers/review_requests_controller.rb
> +      raise ArgumentError, 'tag size is too long' if tag.size > MAX_TAG_SIZE
cf. https://github.com/kotarou1192/Co-review/pull/20#discussion_r379882473

2020-02-16 08:15 UTC, kotarou1192 commented on app/controllers/review_requests_controller.rb
> +      raise ArgumentError, 'tag size is too long' if tag.size > MAX_TAG_SIZE
了解しました！

2020-02-16 08:22 UTC, ikngtty commented
> そこはバリデーション書くべき場所なのですが、今回の場合は特に何もなくてもおｋだったので（タグがない場合等ある）書きませんでした。
> タグの同時重複登録等については例外で処理しているので総合的に多分問題ないと思います。

普通の Ruby のクラスだったらプロパティ用意しないと値入れられないじゃん。
なんでプロパティ定義しなくていいの？その仕様の意味何？っていう根本的な疑問がある。あと、プラクティスとしてその仕様には頼っちゃっていいの？ @radix-soup

2020-02-16 08:24 UTC, kotarou1192 commented on app/controllers/review_requests_controller.rb
> +  MAX_TAG_SIZE = 16
16文字です
lengthのほうがよかったですね。

2020-02-16 08:25 UTC, kotarou1192 commented on app/controllers/review_requests_controller.rb
> +      Tag.new(tag_name: tag, request_id: id, is_pinned: true)
それはそうです、タグを投稿者が設定した時点でピン止めされたとみなして、あとからピン止め外せるように、と考えていました。

2020-02-16 08:27 UTC, kotarou1192 commented on app/controllers/review_requests_controller.rb
> +  def create_tag_record(id = nil)
日本語でエラーメッセージ表示したいので、とりあえずそのままにしておいてみます。

2020-02-16 08:28 UTC, ikngtty commented on app/controllers/review_requests_controller.rb
> +  MAX_TAG_SIZE = 16
難しいところやな。
個人的には length の方がしっくりくるけど、それは他の言語の価値観っぽい気もする。
Ruby 的には `String#size` も `String#length` も文字数を表すみたいね。だからまあ size でもいいのかな。
[IMO] 伝わりにくいところではあるので、コメントでの補足ぐらいは欲しいかな。
はっきり文字数としか思えない名前があればそれが一番いいんだけど、思いつかない。

2020-02-16 08:31 UTC, ikngtty commented on app/controllers/review_requests_controller.rb
> +      Tag.new(tag_name: tag, request_id: id, is_pinned: true)
[Q] タグ数の限度 10 個って、固定タグと変動タグ合わせて 10 ？
投稿者が固定タグ 10 個設定しちゃったら、他のユーザーはタグ設定する余地ないってこと？

他のサービスとかがどういう仕様になってるか気になるな。
固定タグの上限はもうちょっと少なめ、とかになってそうな気がする。わかんないけど。

2020-02-16 08:32 UTC, kotarou1192 commented on app/controllers/review_requests_controller.rb
> +  MAX_TAG_SIZE = 16
コメントを追加しておきます。

2020-02-16 08:32 UTC, kotarou1192 commented on app/controllers/review_requests_controller.rb
> +      Tag.new(tag_name: tag, request_id: id, is_pinned: true)
ニコニコ動画は11個までだったのでとりあえず10個にしておきました。

2020-02-16 08:35 UTC, ikngtty commented on app/controllers/review_requests_controller.rb
> +      Tag.new(tag_name: tag, request_id: id, is_pinned: true)
Q に答えて

2020-02-16 08:37 UTC, kotarou1192 commented on app/controllers/review_requests_controller.rb
> +      Tag.new(tag_name: tag, request_id: id, is_pinned: true)
固定タグと変動タグっていう概念が存在するのかが不明です。
現状含めて10個です。

2020-02-16 08:39 UTC, ikngtty commented on app/controllers/review_requests_controller.rb
> +      Tag.new(tag_name: tag, request_id: id, is_pinned: true)
固定タグって概念があるサイトの場合はどうなってるだろう。私、気になります！（調べてくれと言っているわけではない）。

2020-02-16 08:45 UTC, ikngtty commented on app/controllers/review_requests_controller.rb
> +    redirect_to "/review_requests/#{@review_request.id}"
[Q] URL 直書きじゃなくて、もっといい参照方法なかったっけ？ @radix-soup

2020-02-16 08:51 UTC, ikngtty commented on app/controllers/review_requests_controller.rb
> +    @tags = params[:tags]
[NITS] `@tags` に値入れるのは、再表示時のための処理だと思うんだけど、これは `all_tags_valid?` （タグ群のバリデーションチェック）っていうメソッド名と全然関係ないよね。場所がおかしいと思う。
実際、「あれー `@tags` に値入れてるはずなんだけどどこだ〜？」とずいぶん探してしまった。

2020-02-16 08:56 UTC, kotarou1192 commented on app/controllers/review_requests_controller.rb
> +  def same_name?(all_tags)
tag_duplicate?にします、移動するかどうかは検討してみます。

2020-02-16 08:57 UTC, kotarou1192 commented on app/views/review_requests/new.html.erb
> +      <input id="tags" name="tags" value="<%= @tags %>" type="text" class="post-request__interface post-request__interface_input-tags">
試してみます

2020-02-16 08:58 UTC, kotarou1192 commented on app/views/review_requests/new.html.erb
> +      <input id="tags" name="tags" value="<%= @tags %>" type="text" class="post-request__interface post-request__interface_input-tags">
@tag_names_textに名前を変更します

2020-02-16 08:59 UTC, kotarou1192 commented on app/controllers/review_requests_controller.rb
> +    @tags = params[:tags]
完璧に間違えていました。移動しておきます。

2020-02-16 08:59 UTC, kotarou1192 commented on app/controllers/review_requests_controller.rb
> +    raise ArgumentError, 'too many tags' if all_tags.size > MAX_TAGS_AMOUNT
変更しました、あとでプッシュします。

2020-02-16 09:09 UTC, kotarou1192 commented on app/views/review_requests/new.html.erb
> +      <input id="tags" name="tags" value="<%= @tags %>" type="text" class="post-request__interface post-request__interface_input-tags">
大丈夫でした。

2020-02-16 09:15 UTC, ikngtty commented
[FYI] 気づいてるかもしんないけど一応。
7ea58f6facd378ef0e987ba7a9213b2378fd18e4 のコミットメッセージ、valiable -> variable ね。
コミットメッセージ直すと force push で上書きになって、前後関係がわけわかんなくなるので、放置でおk。

2020-02-16 09:16 UTC, ikngtty commented on app/views/review_requests/new.html.erb
> +        <input id="tags" name="tags" value="<%=@tags%>" type="text" class="post-request__interface post-request__interface_input-tags">
[FYI] コミットのあるべき姿としては、

コミットメッセージが（日本語でいうと）「エラー時にも入力したタグが消えないようにした。」。
コミットコードが、コントローラー内で `@tags` に値を入れるコードと、ビュー内のこのコードのセット。

という感じ。そうすると意図が良く伝わる。

「〜〜をしました。」で終わらせてしまうと、レビュワーは「なんで？」をいちいち考えないといけない。
自明でない限り、目的や意図を書いて欲しい。むしろそっちの方が大事。「〜〜をしました。」は正直コード見れば分かる。

2020-02-16 09:16 UTC, ikngtty commented on app/views/review_requests/new.html.erb
> +        <input id="tags" name="tags" value="<%=@tags%>" type="text" class="post-request__interface post-request__interface_input-tags">
あ、これはコミット 989086b41baaa2542b670f5ed9c22bed5546b452 に対するコメントね。

2020-02-16 09:24 UTC, ikngtty commented on app/controllers/review_requests_controller.rb
> +      Tag.new(tag_name: tag, request_id: id, is_pinned: true)
ごめんこれ終了してるか曖昧やね。
あとで参照しそうな会話なので resolve はしたくないんだけど、レビュー内容としては完結してます。

2020-02-16 09:24 UTC, kotarou1192 commented on app/views/review_requests/new.html.erb
> +        <input id="tags" name="tags" value="<%=@tags%>" type="text" class="post-request__interface post-request__interface_input-tags">
了解です。できるだけ今後気を付けてみます。（すでにいくつかコミット積んじゃったのでまたあれば言ってください）

2020-02-16 09:27 UTC, ikngtty commented on app/controllers/review_requests_controller.rb
> +    !(all_tags.size - all_tags.uniq.size).zero?
ごめん all_tags は Tag クラスの配列のことなんだとずっと勘違いしてた。取り消しました。

[IMO] できれば tag と tag_name をはっきり区別して書いて欲しい。

2020-02-16 09:29 UTC, ikngtty commented on app/views/review_requests/new.html.erb
> +      <input id="tags" name="tags" value="<%= @tags %>" type="text" class="post-request__interface post-request__interface_input-tags">
できれば、なんで大丈夫なのかも調べといて欲しいな。
[Q] 最低限、HTML がどうなってるのかだけでも教えて。
@radix-soup なんか知ってたら教えて。

2020-02-16 09:34 UTC, kotarou1192 commented on app/views/review_requests/new.html.erb
> +      <input id="tags" name="tags" value="<%= @tags %>" type="text" class="post-request__interface post-request__interface_input-tags">
現状何故大丈夫なのかわからないので調べておきたいと思います。
これはタグ名にa" a" f"と入力した時のものです（fだけちょっとスペースひとつ多いのは入力の時のミスです）
<img width="376" alt="スクリーンショット 2020-02-16 18 31 12" src="https://user-images.githubusercontent.com/51397938/74602343-d38ca280-50ea-11ea-8616-302384d6a0ef.png">

2020-02-16 09:40 UTC, kotarou1192 commented on app/views/review_requests/new.html.erb
> +      <input id="tags" name="tags" value="<%= @tags %>" type="text" class="post-request__interface post-request__interface_input-tags">
それと同じことが多分起きるであろうパターンも試しましたが同じく問題なしでした。
自動絵エスケープされてるんでしょうか？
タイトルと本文にもダブルクオートを入れました
<img width="388" alt="スクリーンショット 2020-02-16 18 39 09" src="https://user-images.githubusercontent.com/51397938/74602445-d340d700-50eb-11ea-9202-ca8ef5bd0861.png">

2020-02-16 09:44 UTC, ikngtty commented
17a552944e103fa4a938891dd07aba3cede133c5 のコミットメッセージだけど、

```
update: change error messages to Japanese ones
```

とか？（文法は自信無い）

ユーザーに向けた表示メッセージが変わってる以上、これは機能のアップデートであり、リファクターや cosme の類では無い。

2020-02-16 09:45 UTC, ikngtty requested changes

2020-02-16 09:45 UTC, ikngtty commented on app/controllers/review_requests_controller.rb
> +  # tag length
[MUST] ごめん、これでは説明になってない。てか length で説明になると思うなら、最初から定数名を LENGTH に変えればいいだけでは？
何が言いたいかわからなすぎて最早怖いコメントになってる。これなら無い方がマシ。

説明が難しかったら、具体例とかを使ってもいい。

```rb
# NOTE: the size of "ぬ" is 2.
```

みたいな。
マルチバイト文字問題が英語には無い問題である以上、このような形でコメントに日本語が出てくるのはしょうがない。欧米人だろうとこうやって "ぬ" とか書かざるを得ない場面だと思う。

ちなみに、ひらがなとして "ぬ" を選んだのはボーボボの影響。

2020-02-16 09:46 UTC, ikngtty commented
4c857115f290f49636312c61f048e0440fad474d
コミットメッセージに反し、違う修正が混ざってる。
コミット前に差分をしっかり確認すること。

2020-02-16 09:49 UTC, ikngtty requested changes

2020-02-16 09:49 UTC, ikngtty commented on app/controllers/review_requests_controller.rb
> +      raise ArgumentError, 'タグ名が長すぎます。16文字までにして下さい。' if tag.size > MAX_TAG_SIZE
[MUST] ちゃんと定数を使って。でないと定数の値変えた時にここで乖離が出てしまう。
ちなみに全角数字か半角数字かも統一すること。

2020-02-16 09:50 UTC, kotarou1192 commented on app/controllers/review_requests_controller.rb
> +  # tag length
了解です、正直なんて書いていいかわからなくて適当に書いてしまいました。
修正しますね。

2020-02-16 09:56 UTC, ikngtty commented on app/views/review_requests/new.html.erb
> +      <input id="tags" name="tags" value="<%= @tags %>" type="text" class="post-request__interface post-request__interface_input-tags">
えーどうなってるんだこれ。もしかして HTML パーサーが優秀なのか？

`"> <input type="text` とか入れたらどうなる？テキストボックス増えたりしない？

2020-02-16 10:13 UTC, ikngtty commented on app/controllers/review_requests_controller.rb
> +  # tag length
間違えた。size は 2 じゃなくて 1 やね。

2020-02-16 11:09 UTC, kotarou1192 commented on app/views/review_requests/new.html.erb
> +      <input id="tags" name="tags" value="<%= @tags %>" type="text" class="post-request__interface post-request__interface_input-tags">
増えませんでした。どう言うことだろう？
<img width="363" alt="スクリーンショット 2020-02-16 20 09 02" src="https://user-images.githubusercontent.com/51397938/74603578-37699800-50f8-11ea-9fce-311b4acb0dde.png">

2020-02-16 11:11 UTC, kotarou1192 commented
変更しました。
多分これで全てできたと思います。
<img width="729" alt="スクリーンショット 2020-02-16 20 10 45" src="https://user-images.githubusercontent.com/51397938/74603591-74ce2580-50f8-11ea-8387-17f6b5c0b207.png">

2020-02-16 13:02 UTC, ikngtty commented on app/controllers/review_requests_controller.rb
> +    raise ArgumentError, 'タグ名が重複しています。' if tag_duplicate?(all_tags)
気づかんかった。ナイス。

2020-02-16 13:10 UTC, ikngtty requested changes

2020-02-16 13:10 UTC, ikngtty commented on app/controllers/review_requests_controller.rb
> +  # # NOTE: the size of "aa" is 2.
[MUST] マルチバイト文字を例にしないと意味がない。
ascii 文字は 1 文字 1 バイトだから、これじゃ結局バイト数なのか文字数なのか区別できてない。

[MUST] あと、`#` が二重になってる。

2020-02-16 15:04 UTC, kotarou1192 commented on app/controllers/review_requests_controller.rb
> +  # # NOTE: the size of "aa" is 2.
Rubyってバイト数意識する機会今まで遭遇したことがないのですが、意識して書く必要あるのでしょうか？
＃完全に気づきませんでした、修正します

2020-02-16 15:11 UTC, Raclett3 commented on app/controllers/review_requests_controller.rb
> +  # # NOTE: the size of "aa" is 2.
ASCII文字は1バイト1文字なのですが、マルチバイト文字、例えば日本語の文字等は1文字を表すのに2バイト以上必要なので、文字数とバイト数が一致しないんですよね。そのため、SIZEというだけの名前で、かつASCII文字の例しかないとSIZEは文字数とバイト数のどっちを指しているんだろう、という疑問が残ることになります。

2020-02-16 16:39 UTC, ikngtty commented on app/controllers/review_requests_controller.rb
> +  # # NOTE: the size of "aa" is 2.
Discord にて解決。

2020-02-16 16:40 UTC, ikngtty commented on app/controllers/review_requests_controller.rb
> +    raise ArgumentError, 'too many tags' if all_tags.size > MAX_TAGS_AMOUNT
> あとページのどこかにも書いた方が。
無い方が自然な気もしてきた。任せた。修正せずそのままでいいと思うなら Resolve conversation してくれ。

2020-02-16 16:42 UTC, kotarou1192 commented on app/controllers/review_requests_controller.rb
> +    raise ArgumentError, 'too many tags' if all_tags.size > MAX_TAGS_AMOUNT
リクエスト書き込みページまだテスト段階なので、とりあえず現時点ではこのままで行きますね。

2020-02-16 17:03 UTC, ikngtty commented on app/views/review_requests/new.html.erb
> +      <input id="tags" name="tags" value="<%= @tags %>" type="text" class="post-request__interface post-request__interface_input-tags">
動かしてみて思ったけど、これ turbolinks のおかげか、HTML を書き換えずに JS で処理されてるっぽいな。
JS で `textbox.value = '"> <input type="text'` ってやってるんだとしたら、変に HTML タグの外側にはみ出して解釈されたりしないのも頷けるわ。
takashiiiii の見てるそのデバッグ HTML は、実際の HTML ではなく、JavaScript で書き換えられた DOM を仮想的に表現した HTML なんだと思う。
画面上で右クリックして「ページのソースを表示」すれば、実際の HTML が見えるよ。初期表示時から何も変わってないやつ。

2020-02-17 10:31 UTC, ghost requested changes
@ikngtty がクリティカルな指摘をしてくれたので，細かい指摘が多くなってしまった．
主に，命名について指摘したので，今後は”一目瞭然”を意識して命名に気を遣ってみて欲しい．

2020-02-17 10:31 UTC, ghost commented on app/controllers/review_requests_controller.rb
> +  MAX_TAGS_AMOUNT = 10
[IMO]ここは付与可能タグ数の最大値なので，もうちょっといい名前がありそう．
e.g. MAX_TAGS_COUNT, TAGS_COUNT_LIMIT

2020-02-17 10:31 UTC, ghost commented on app/controllers/review_requests_controller.rb
> +  MAX_TAG_SIZE = 16
[IMO] ここも，タグごとの文字数，を示すことがわかりにくい．
e.g. MAX_TAG_CHARS, TAG_CHARS_LIMIT

2020-02-17 10:31 UTC, radix-soup commented on app/controllers/review_requests_controller.rb
> +    redirect_to "/review_requests/#{@review_request.id}"
@ikngtty cc: @kotarou1192 
[FYI] `"/review_requests/#{@review_request.id}"` 相当の記述を以下に挙げる

```ruby
redirect_to @review_request
redirect_to review_request_url(id: @review_request.id)
```
参考：https://qiita.com/higeaaa/items/df8feaa5b6f12e13fb6f

2020-02-17 10:31 UTC, radix-soup commented on app/controllers/review_requests_controller.rb
> +    raise ArgumentError, 'タグ名が重複しています。' if tag_duplicate?(all_tags)
[NITS] `'タグ名が重複しています。'` という部分，ちょっと日本語が不親切に思える．
"タグ名"hoge" はすでに登録されています．" 等にした方がいいと思う．

2020-02-17 10:31 UTC, radix-soup commented on app/controllers/review_requests_controller.rb
> +      Tag.new(tag_name: tag, request_id: id, is_pinned: true)
[NITS] `is_pinned`の名前が気になる．Ruby の標準的な命名規則だと bool を格納するパラーメータは `pinned?` のようになるはず．
[FYI] https://stackoverflow.com/questions/3112078/rails-boolean-fields-is-foo-or-just-foo

2020-02-17 10:31 UTC, radix-soup commented on app/controllers/review_requests_controller.rb
> +    all_tags = params[:tags].split(/[ |　]/)
[IMO] `split(/[ |　]/)` 内の正規表現が一瞬何してるかわかんなかった．僕なら以下のように書く(けど好みの問題かも)
`all_tags = params[:tags].split(/[[:blank:]]/)` <- これだと全角white_space も tab でも分割できる．
連続したwhite_space も除去したいなら
`all_tags = params[:tags].split(/[[:blank:]]+/)`

2020-02-17 10:46 UTC, radix-soup commented
@ikngtty 
> [17a5529](https://github.com/kotarou1192/Co-review/commit/17a552944e103fa4a938891dd07aba3cede133c5) のコミットメッセージだけど、
> 
> ```
> update: change error messages to Japanese ones
> ```
> 
> とか？（文法は自信無い）

[IMO] 
僕なら
```
update: adopt Japanese error-message
```
とか書く

2020-02-17 11:05 UTC, ikngtty commented on app/controllers/review_requests_controller.rb
> +  MAX_TAGS_AMOUNT = 10
[FYI] amount は「個数」というより「量」って感じがして、このスケールではあんま使わないイメージ。俺もこういう時は大体 count 使うな。
あと limit は「以下」なのか「未満」なのかわかりづらいことがあるので個人的には max の方が好き。

2020-02-17 11:36 UTC, radix-soup commented on app/controllers/review_requests_controller.rb
> +      Tag.new(tag_name: tag, request_id: id, is_pinned: true)
@ikngtty cc: @kotarou1192 
[FYI] `acts-as-taggable-on` という，Rails で比較的リッチなタグ機能を実装するための gem．この gem の README に，参考になりそうなことが書いてある．我々の文脈でいう固定タグというのが，下記リンク先の"Owned Tag" に相当しそう．詳しくはリンク参照．
https://github.com/mbleigh/acts-as-taggable-on#tag-ownership

2020-02-17 11:43 UTC, radix-soup commented on app/controllers/review_requests_controller.rb
> +  MAX_TAGS_AMOUNT = 10
@kotarou1192 
@ikngtty も指摘してる通り：
[NITS] Amount は l(リットル) とか，m^3(立方メートル) とかの連続量について使うイメージ．自然数との対応が取れる countable な量に関しては，慣習的に `count` を使うイメージでいい．
一つ前のコメントでの `limit` に対する意見(「以下」なのか「未満」なのかわかりづらい) は妥当なので，総合してここの命名は `MAX_TAGS_COUNT` に修正したい．

2020-02-17 11:44 UTC, radix-soup commented on app/controllers/review_requests_controller.rb
> +  MAX_TAG_SIZE = 16
[IMO] `MAX_TAG_COUNT` への修正にしたがって，ここの命名も `MAX_TAG_CHARS_COUNT` に修正したい

2020-02-17 11:54 UTC, ikngtty commented on app/controllers/review_requests_controller.rb
> +    all_tags = params[:tags].split(/[ |　]/)
何これ初めて知った。使えるの Ruby だけ？

2020-02-17 11:55 UTC, ikngtty commented on app/controllers/review_requests_controller.rb
> +  MAX_TAGS_AMOUNT = 10
金額とかは一応離散量だけど、感覚的には連続量に近いのかね。
その辺考慮して、漠然と「量ってイメージ」って言ってみた。

2020-02-17 11:56 UTC, ikngtty commented on app/controllers/review_requests_controller.rb
> +  MAX_TAGS_AMOUNT = 10
あ、limit の分かりづらさに関してはリーダブルコードにも載ってた気がするそういえば

2020-02-17 11:59 UTC, radix-soup commented on app/controllers/review_requests_controller.rb
> +    all_tags = params[:tags].split(/[ |　]/)
posix の空白演算子を使った記法だね．
[FYI] https://konbu13.hatenablog.com/entry/2014/03/02/213742
僕はRuby でしか使ったことがない．Ruby のこの辺の機能拡張は大抵 Perl からの引き写しなので，おそらく Perl でも使えるんじゃないだろうか．

2020-02-17 11:59 UTC, ikngtty commented
Discord でちょっと予告したけど、 https://github.com/kotarou1192/Co-review/pull/20#discussion_r380085717 に関しては

[MUST]

かなーと感じる。（なんで直した方がいいか分かる？ @kotarou1192 ）

2020-02-17 12:01 UTC, ikngtty commented on app/controllers/review_requests_controller.rb
> +    redirect_to "/review_requests/#{@review_request.id}"
じゃあ個人的にここの修正は
[MUST]
かなー。（直した方がいい理由分かる？ @kotarou1192 ）

2020-02-17 12:02 UTC, radix-soup commented on app/controllers/review_requests_controller.rb
> +  MAX_TAGS_AMOUNT = 10
手元のリーダブルコード参照した．載ってたわ．失念していた．反省．
以下『リーダブルコード』から引用．

>制限関連なら limit ではなく min/max を用いる
> 範囲指定なら first/last, begin/end を用いる（それぞれ包括/排他的意味[以下/未満]が異なる）

2020-02-17 12:06 UTC, radix-soup commented on app/controllers/review_requests_controller.rb
> +    all_tags = params[:tags].split(/[ |　]/)
僕はこの posix 記法，`:blank:`部分が明示的に空白文字を表現していて可読性高いと感じるけど，もしかしたら一般的ではないのかも．あくまで nit pick ，好みの問題ということで．

2020-02-17 12:07 UTC, ikngtty commented on app/controllers/review_requests_controller.rb
> +    raise ArgumentError, 'タグ名が重複しています。' if tag_duplicate?(all_tags)
ユーザーの入力したタグが既存のタグと衝突した場合のエラーメッセージだとしたら、「すでに登録されています」が確かに適してると思う。
だけど実際は、ユーザーの入力した複数のタグの中に重複がある場合のエラーメッセージなんだよねこれは。
それ踏まえると「重複しています。」で正しいと思うし、「すでに登録されています。」の方が変だと思う。

ただ、「タグ名"hoge"が」を加えた方が親切なのはその通りだと思う。
エラー対象のタグが赤くハイライトされたりとか、そういうのもまだ無いしね。

2020-02-17 12:08 UTC, radix-soup commented on app/controllers/review_requests_controller.rb
> +    !(all_tags.size - all_tags.uniq.size).zero?
> tag と tag_name をはっきり区別
さらっと読んでたけど，個人的にはここ [MUST] かな

2020-02-17 12:09 UTC, ikngtty commented on app/controllers/review_requests_controller.rb
> +    all_tags = params[:tags].split(/[ |　]/)
posix かよ神

2020-02-17 12:14 UTC, radix-soup commented on app/controllers/review_requests_controller.rb
> +    raise ArgumentError, 'タグ名が重複しています。' if tag_duplicate?(all_tags)
> だけど実際は、ユーザーの入力した複数のタグの中に重複がある場合のエラーメッセージ

そうか，勘違いしたわ．だとしたら”重複しています”の方が妥当だね．
踏まえて，修正の方向としては `タグ名: "hoge" が重複しています` というエラーメッセージになればいいかな．

2020-02-17 12:43 UTC, ArakiTakaki reviewed
全く関係無い部分で申し訳ないです😢
個人的にきになる点をコメントしました。
BEMという設計ルールの場合

~~せっかくRubyを入れているのでscssの方が設計としてはマッチしていると思います。~~
~~ただ、まぁ、手が疲れないのと見通しが良いというメリット以外は無いのですが。~~

にむさんの好意で入れない判断を下したのですね、すみません🙇‍♂️

2020-02-17 12:43 UTC, ArakiTakaki commented on public/css/post-request.css
> +  margin-bottom: 10px;
nits:
ここは`margin: 10px 0`にしたほうがスマートかと思います。
https://developer.mozilla.org/ja/docs/Web/CSS/margin

全てをショートハンドにすれば良いというわけではないのですが、基本的に`padding`と`margin`はショートハンドで記述を行う方がスマートになります。

意味を持たせる場合のみ`margin-top`などを使用する方が無難かと思われます。

2020-02-17 12:43 UTC, ArakiTakaki commented on app/views/review_requests/new.html.erb
> +      <input id="tags" name="tags" value="<%= @tag_names_text %>" type="text" class="post-request__interface post-request__interface_input-tags">
nits:
該当ソースをしっかり読んだわけではないので見当違いでしたら申し訳ないです。

Modifireを使用すればなんとかならないでしょうか？
https://qiita.com/usagi-f/items/b4e56e765384c49d5d04

基本的に`interface`など非常に広義なものはCSSの特性上混乱を招くことが多いと経験則では思います。
あと、今回の場合はmodifireにあたると思っています。

post-request__interface
post-request__interface_input-tags
となりますが
個人的に

post-request__input-tags
post-request__input-tags--email
post-request__input-tags--name

という設計になるのが正ではないでしょうか。

2020-02-17 13:13 UTC, radix-soup commented
https://github.com/kotarou1192/Co-review/pull/20#issuecomment-586680737
補足．
@ikngtty , @kotarou1192 
ここで，`Tag` クラスは `ApplicationRecord` のサブクラスとして定義しているだけ．これ自体は，Active Recordモデルの作成と

2020-02-17 13:33 UTC, radix-soup commented
https://github.com/kotarou1192/Co-review/pull/20#issuecomment-586680737
補足．
@ikngtty , @kotarou1192 

> なんでプロパティ定義しなくていいの？

ここで，`Tag` クラスは `ApplicationRecord` のサブクラスとして定義されている．これ自体，Active Recordモデルの作成として問題ない．
というのは，この記述だけで ActiveRecord は Tag モデルを作成し，データベースのTags テーブルにマッピングする．
さらに，Tags テーブルに含まれている各行のカラムを，作成したモデルのインスタンスの属性にマッピングする．
なので，プロパティが未設定でもActiveRecord の魔法の力でどうにかなってしまう．

結論：この仕様に頼ることはバッドプラクティスではない．

2020-02-17 13:40 UTC, radix-soup commented on app/views/review_requests/new.html.erb
> +      <input id="tags" name="tags" value="<%= @tags %>" type="text" class="post-request__interface post-request__interface_input-tags">
そう，turbolinks のおかげ．Ajax で取得したDOMを適宜 merge/replace している．uri まわりもHistoryAPI を叩いて変更している(はず．

2020-02-17 14:06 UTC, ikngtty commented
あ、そうか。データベースに定義があるからか。納得。
定義してないプロパティを自由に後付けできるオブジェクトに見えてしまっていた。

2020-02-17 14:13 UTC, ikngtty commented
RDB なの完全に忘れてて、save したオブジェクトに合わせてカラム定義が勝手に生成されてくれるみたいなのイメージしちゃってたんだよななぜか。逆だったわ。あまりに Rails 初心者。

2020-02-17 17:40 UTC, kotarou1192 commented on app/controllers/review_requests_controller.rb
> +    all_tags = params[:tags].split(/[ |　]/)
blankにしておきます。（タブを考慮してなかった）

2020-02-17 17:44 UTC, kotarou1192 commented on app/controllers/review_requests_controller.rb
> +  MAX_TAGS_AMOUNT = 10
MAX＿TAGS＿COUNTにしました。

2020-02-17 17:56 UTC, kotarou1192 commented on app/controllers/review_requests_controller.rb
> +    raise ArgumentError, 'タグ名が重複しています。' if tag_duplicate?(all_tags)
重複しているタグ名の表示は今後の課題にしておいたほうがいいとおもいます、修正が大きくなりすぎるような気がします。
実際にやる場合の方針として、先にタグ名の長さで例外をかけているのでMAX＿TAGS＿COUNT個までしかタグが来ないという前提でループでタグを全て回して、重複している物を抜き出すという感じでどうでしょうか。

2020-02-17 17:58 UTC, kotarou1192 commented on app/controllers/review_requests_controller.rb
> +      Tag.new(tag_name: tag, request_id: id, is_pinned: true)
了解しました、pinnedに修正しておきます。

2020-02-17 18:22 UTC, kotarou1192 commented on public/css/post-request.css
> +  margin-bottom: 10px;
変更しておきました。

2020-02-17 18:29 UTC, kotarou1192 commented
cosme: remove comment for max_tags_size
間違えてcosmeにしましたがremoveです。
上にある修正全て終わりました。

2020-02-17 18:33 UTC, kotarou1192 commented on app/controllers/review_requests_controller.rb
> +    redirect_to "/review_requests/#{@review_request.id}"
直したほうがいい理由はわからないですが、直しておきます。
やっていることは同じに見えます。可読性の問題ですか？

2020-02-17 18:44 UTC, kotarou1192 commented on app/controllers/review_requests_controller.rb
> +    !(all_tags.size - all_tags.uniq.size).zero?
```Ruby
all_tags.map do |tag|
```
```Ruby
all_tags.map do |tag_name|
```
修正しました

2020-02-18 04:26 UTC, ikngtty commented on app/controllers/review_requests_controller.rb
> +    redirect_to "/review_requests/#{@review_request.id}"
可読性もなくはないけど、一番は「ルーティング（URL）が変わっても対応できる」ってとこかな。つまり保守性。

マジックナンバーに定数使う状況と似てるかな。
「16」という数字ではなく「最大タグ数」にこそ用がある。
「"/review_requests/xx"」という URL ではなく「@review_request のページ」にこそ用がある。
そして後者を参照していれば、前者の値が変わっても自動で対応されるってわけ。

`MAX_TAGS_COUNT = 16`
をどこかで定義してるのと同じように、
`review_request の URL は "/review_requests/xx"`
って定義が `config/routes.rb` にあるんだよね。

まあ実際は
`resources :review_requests`
としか書いてないんだけど、とにかくここで設定していて、設定を変えようと思えば変えられることに違いはない。

2020-02-18 04:31 UTC, ikngtty commented on app/controllers/review_requests_controller.rb
> +    raise ArgumentError, 'タグ名が重複しています。' if tag_duplicate?(all_tags)
> 今後の課題にしておいたほうがいいとおもいます

ほんまやね。ナイス指摘。修正コスト考えてなかったわ。
Trello でカード切っておいて。

2020-02-18 04:35 UTC, ikngtty commented on app/controllers/review_requests_controller.rb
> +    raise ArgumentError, 'タグ名が重複しています。' if tag_duplicate?(all_tags)
> 実際にやる場合の方針
> ループでタグを全て回して、重複している物を抜き出すという感じ

そうだね。

> 先にタグ名の長さで例外をかけているので

「タグの個数」の間違い？なんか文章つながらないけど。

> MAX＿TAGS＿COUNT個までしかタグが来ないという前提で

これ関係あんのかな。入力されたタグを全部調べるだけかと思ったけど。

2020-02-18 04:36 UTC, ikngtty commented
[IMO] コミットメッセージにある程度一意性が欲しい（２回目）

2020-02-18 04:42 UTC, ikngtty commented on app/controllers/review_requests_controller.rb
> +    !(all_tags.size - all_tags.uniq.size).zero?
まだあるよ。ちゃんと `tag` とか `tags` とかで全部検索して。

2020-02-18 04:44 UTC, ikngtty commented on app/controllers/review_requests_controller.rb
> +    !(all_tags.size - all_tags.uniq.size).zero?
てか、俺の勘違いを産んだこの `all_tags` すら直ってない。`all_tag_names` にして。

2020-02-18 04:47 UTC, ikngtty commented
努力目標なんだけど、次からなるべくプッシュ前にコミット整理する癖つけよう。
例えば 06d7716 ef1041c この２つなんかひとまとめにしたいよね。

2020-02-18 04:48 UTC, ArakiTakaki commented
> 間違えてcosmeにしましたがremoveです。

https://www.granfairs.com/blog/staff/git-commit-fix
運用でカバーをするのではなく、変更を行うとレビュアーとしては楽になるのでおすすめです！
git rebase -i おすすめ！

2020-02-18 05:12 UTC, ikngtty commented
PR してるブランチでプッシュ後の rebase -i -> force push は、やっていいか意見分かれるかなーと思ったり。
個人的にはレビューとの時系列狂うから嫌かな。

だからこそプッシュ前に見直ししてほしいんよね。

2020-02-18 05:17 UTC, kotarou1192 commented on app/controllers/review_requests_controller.rb
> +    !(all_tags.size - all_tags.uniq.size).zero?
タグのレコードに関するところはtagsにして、それ以外はtag_nameで統一しました。変更を後でプッシュします。

2020-02-18 05:20 UTC, kotarou1192 commented on app/controllers/review_requests_controller.rb
> +    raise ArgumentError, 'タグ名が重複しています。' if tag_duplicate?(all_tags)
タグの個数の間違いです。申し訳ないです。
先に例外をかけない場合だとタグが1万個入力されたらすごいループ数になるので危険です。その点先にタグの個数を制限しているので今回の場合はループでも安全です。

2020-02-18 05:23 UTC, ikngtty commented
[FYI] ちなみにコミットコメントだけど、"look" の使い方がおかしい感じする。

まず ed4c8d4 に関しては文法がおかしい。
"make xxx look better" の方は合ってるんだけど、これがどういう構造なのか理解してるかな。
間違った理解のまま ed4c8d4 のコメントに応用しちゃってる気がする。

次にそもそも論なんだけど、単に
"make xxx better" (look 無し）
じゃだめなん？

2020-02-18 05:41 UTC, kotarou1192 commented
コメントをぶら下げて返せなくなってるのでこちらで。
「何々を変えた」ではなく、「何のために変更した」にする必要があるということですか？
一意性ってそれをみただけでひとつに定まるというように理解しています。
コミットメッセージにどういうことを書けばいいかいまいち理解してないかもです。

2020-02-18 05:42 UTC, kotarou1192 commented
「何々のため」にあたる部分がプレフィックスで、その後に続く本文には変更を書けばいいと思っていました。

2020-02-18 05:44 UTC, kotarou1192 commented
Lookの使い方に関しては確かにおかしいかもとは思いましたが、雑にそのまま適当に書いてしまいました。
もう少し調べて書かないと練習にならないよなって反省しています。今後も何かあれば指摘お願いします。

2020-02-18 05:59 UTC, kotarou1192 commented
今回の３コミットは結構気をつけたのですが、このコミットの仕方で一意性がまずかったりしますか？
もしまずかったら教えて下さい、逆におkだったら今後このようにできる限りしてみます

2020-02-18 06:09 UTC, ikngtty commented
> 一意性

コメントを見ただけで修正内容が一意に特定できるようにしてほしい。
コメントだけでコミットが区別できるようにしてほしい。
コメントがなるべく他と被らないようにしてほしい。
そんなイメージで言った。

rename constants
じゃ全然内容絞れないし被りまくってるから、NG。

2020-02-18 06:10 UTC, ikngtty commented
> コメントをぶら下げて返せなくなってるのでこちらで。

もっと上にスレの本体ない？そっちにコメントできるはず。
Discord のログ参照。俺も一回それで引っかかってる。

2020-02-18 06:26 UTC, kotarou1192 commented
> コメントを見ただけで修正内容が一意に特定できるようにしてほしい。
コメントだけでコミットが区別できるようにしてほしい。
コメントがなるべく他と被らないようにしてほしい。
そんなイメージで言った。

rename constants
じゃ全然内容絞れないし被りまくってるから、NG

なるほど、理解しました。今回の場合はRename A to Bみたいな感じにすべきだったということですね。
以後気を付けてみます。

2020-02-18 13:41 UTC, ikngtty commented on app/controllers/review_requests_controller.rb
> +    raise ArgumentError, 'タグ名が重複しています。' if tag_duplicate?(all_tags)
そういう意味か。うん、いいと思う。

ちなみに一応伝わるから流してたけど、「例外かける」って日本語おかしいから気をつけてね。かけるのは「チェック」だからね。「個数チェックをかける」。

2020-02-18 13:47 UTC, radix-soup commented on app/controllers/review_requests_controller.rb
> +    all_tags = params[:tags].split(/[ |　]/)
タブまで意識するのはちょっとやりすぎかもしれないけど，包括的であるに越したことはないからね．

[FYI] posix キャラクタクラス，取り回しがいいから覚えておくといいよ．
http://www.kt.rim.or.jp/~kbk/regex/regex.html#CLASSNAME

2020-02-18 13:48 UTC, ikngtty commented
[FYI] リネーム時に漏れが多いけど、ちゃんと IDE のリネーム機能使うといいよ。最低でも検索・置換機能は使って欲しい。

2020-02-18 13:51 UTC, ikngtty commented
b52ddd8fa42bb2bae43e5bd1c313211254a922ea これは関連する変更がちゃんと一つのコミットにまとまってて GOOD。こういうコミットを増やしていきたいね。

2020-02-18 13:53 UTC, radix-soup commented
07a061142658b6645c6da18ef09b23a8222cb12e など，
 "make sth better" みたいに使役動詞(make) を使ってるけど，コミットメッセージでは普通使わない．
こういう冗長な構文を避けるためのプリフィクス．

2020-02-18 13:56 UTC, ikngtty requested changes

2020-02-18 13:56 UTC, ikngtty commented on app/controllers/review_requests_controller.rb
> +  MAX_TAG_NAMES_COUNT = 10
[MUST] これに関しては TAG_NAME じゃなく TAG の方が自然。
「最大タグ名数」より「最大タグ数」の方が自然じゃない？

2020-02-18 13:58 UTC, radix-soup commented on app/controllers/review_requests_controller.rb
> +    redirect_to "/review_requests/#{@review_request.id}"
[FYI] @ikngtty 
流石に既知かもだけど一応補足．
`config/routes.rb` 内に `resources :sth` を記述すると， sth に関してRESTful なルーティングが自動生成される．

2020-02-18 14:19 UTC, ghost approved these changes
僕からの指摘は概ね修正されてた．お疲れ様．
あとは resolved にしてない @ikngtty からの `MAX_TAG_NAMES_COUNT` の修正が残ってるけど，僕の担当範疇じゃないので僕はここで一旦 Approve．

2020-02-18 14:44 UTC, ikngtty requested changes

2020-02-18 14:44 UTC, ikngtty commented on app/controllers/review_requests_controller.rb
> +  def all_tag_names_valid?
[MUST] ごめん漏れてた。これも変だわ。
create_tag_record もしてることだし、この関数はタグ名に限らずタグに関する全部のバリデーションチェックを行う関数だと読める。
ので、`all_tag_names_valid?` ではなく `all_tags_valid?` の方が適切。

2020-02-18 14:50 UTC, ikngtty commented
個人的にこの tags はこのままで良いと思うけど、「tag_names にするのは MUST かなー」って言ってた @radix-soup はどう思う？

```rb
params[:tags]
```

2020-02-18 15:17 UTC, radix-soup commented
> 個人的にこの tags はこのままで良いと思うけど、「tag_names にするのは MUST かなー」って言ってた @radix-soup はどう思う？
> 
> ```ruby
> params[:tags]
> ```

僕は [NITS] かな．包含関係として自然なのは `params[:tag_names]` だと思う．
`@tag_names_text` は `tags` のパラメータじゃなくて，`tag_names`のパラメータとして考える方が一般的には妥当だよね

2020-02-18 15:17 UTC, ikngtty commented on app/controllers/review_requests_controller.rb
> +    tags.each(&:save)
今更大事なの見つけてごめん。
[Q] これ、既存のタグと競合したらどうなんの？

ちなみに、もしバグるとしたら fix は別のタスクとして後回しでいいよ。重そうだし。

2020-02-18 15:20 UTC, ikngtty commented
[Q] @radix-soup 
ActiveRecord でトランザクションってどうやって張るの？
`@review_request` を save したあと、`tags.each` を save するという流れは、トランザクションでまとめないとまずい気がする。

2020-02-18 15:30 UTC, radix-soup commented
> [Q] @radix-soup
> ActiveRecord でトランザクションってどうやって張るの？
> `@review_request` を save したあと、`tags.each` を save するという流れは、トランザクションでまとめないとまずい気がする。
@ikngtty cc: @kotarou1192 
[A] モデルのクラスやモデルのインスタンス(普通`ApplicationRecord`) で.transactionを呼び出す．`.transaction` は block を引き受ける．
ちなみに，1つのトランザクションは(モデルのインスタンスではなく)データベース接続に bind されるよ．

2020-02-18 15:39 UTC, ikngtty commented
@radix-soup ふむ、となるとやっぱり

> @review_request を save したあと、tags.each を save するという流れは、トランザクションでまとめないとまずい気がする。

この対応は [MUST] やね。@kotarou1192

新しいタスクとして Trello でカード切っておいたから、これがマージされた後にでも、じっくりやってくれたまへ。
「(review_requests) リクエストとタグを save する際にトランザクションでまとめる」ってやつ。

2020-02-18 18:35 UTC, ArakiTakaki commented on public/css/post-request.css
> +  margin-bottom: 10px;
対応ありがとうございます！

2020-02-19 12:22 UTC, kotarou1192 commented on app/controllers/review_requests_controller.rb
> +    redirect_to "/review_requests/#{@review_request.id}"
自分なりに理解はしましたが、ルーティング変わる場合がいまいち想像できませんでした。
それでもルーティングを無理やり変えた！とかなった場合に、レコードを直接指定している今回の参照方法（リダイレクト）ならそのまま使えるので、もし自分以外がメンテナンスをする場合に問題が発生しにくいということですよね。

2020-02-19 13:29 UTC, ikngtty commented on app/controllers/review_requests_controller.rb
> +    redirect_to "/review_requests/#{@review_request.id}"
そうそう。

> もし自分以外がメンテナンスをする場合に

自分もだよ。「実装した自分なら覚えてるだろう」なんて過信は禁物。絶対考慮し忘れるからこういうの。
明日の自分は基本何も覚えてないと思った方がいい。

> ルーティング変わる場合がいまいち想像できませんでした。

その感覚はまあ多分正しい。実際のところあんまなさそうではある。
そういう意味では、修正 MUST にしたのは実用上の理由よりも、エンジニアとしての生理的感覚って理由の方が大きいかも。

2020-02-19 13:56 UTC, radix-soup commented on app/controllers/review_requests_controller.rb
>      raise ArgumentError, 'タグ名が重複しています。' if tag_name_duplicate?(all_tag_names)
[NITS] `tag_name_duplicate?` -> `tag_name_duplicated?` の方が名前として自然だねここ

2020-02-19 14:21 UTC, kotarou1192 commented on app/controllers/review_requests_controller.rb
> +    tags.each(&:save)
競合するってどういうことでしょうか？
これはリクエスト投稿時のものなので、何も問題なさそうに見えます。
おそらく同じタグ名が別のリクエストにも投稿されたらレコード内でタグ名が重複するということなのでしょうが、それはタグ設計上問題ないです。

2020-02-19 15:50 UTC, radix-soup commented on app/controllers/review_requests_controller.rb
> +      Tag.new(tag_name: tag, request_id: id, is_pinned: true)
test

2020-02-19 16:11 UTC, ikngtty commented on app/controllers/review_requests_controller.rb
> +    tags.each(&:save)
> 同じタグ名が別のリクエストにも投稿されたら

そうそう

> レコード内でタグ名が重複する

「レコード内で」？「テーブル内のレコード間で」かな

> タグ設計上問題ない

あーそうか。そういえばこれ、レビューリクエスト毎のタグを入れるテーブルか。
主キーは request_id と tag_name の２つの組み合わせになるイメージだよね。
tag_name の１つだけかと思って、競合エラー起きるかと思った。すまそ。

このやりとりで気付いた別の指摘事項として以下があるけど、これも別件として Discord で議論 or Trello でカード切るわ。

*    schema.rb を見た限り、主キーが設定されてない気がする。
*   テーブル名が紛らわしい。将来的にタグに関するカラムが増えて、正規化した時のことを考えると、ReviewRequests, TagIDsPerRequest, Tags の３つのテーブルになりそうな感じ。
この時、今の Tags テーブルの役割は、この３つの中では Tags ではなく TagIDsPerRequest の方。というわけで、「Tags という名前で生まれる誤解を防ぐ」「将来ありうる命名を邪魔しない」という２つの理由から、TagIDsPerRequests の方が望ましい。（今テキトーに考えた命名だが、多分もっと良い命名がある。要は、中間テーブルっぽい名前にして欲しい。）（

2020-02-19 17:51 UTC, kotarou1192 commented on app/controllers/review_requests_controller.rb
> +    tags.each(&:save)
テーブル内のレコード間でです
前半読みました

2020-02-19 18:03 UTC, radix-soup commented on app/controllers/review_requests_controller.rb
>      raise ArgumentError, 'タグ名が重複しています。' if tag_name_duplicate?(all_tag_names)
修正確認した．resolve する．

2020-02-19 18:17 UTC, ikngtty approved these changes

2020-02-19 18:18 UTC, merged